return {
    [4197076008] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true
}
