return {
    [4494278135] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true,
    [0] = true
}
